import Head from 'next/head'
import Todo from './TodoList'

export default function Home() {
  return (
    <>
      <Head>
        <title>todo list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Todo/>
      </main>
    </>
  )
}
